backend:
  name: github
  repo: acgd-webdev-workshops/realcottages

media_folder: "images/uploads"

collections:
  - name: "website-settings"
    label: "Website settings"
    files:
      - label: "Website settings"
        name: "site"
        file: "_data/site.yml"
        fields:
          - label: "Tel"
            name: "tel"
            widget: "string"
          - label: "Tel display"
            name: "tel_display"
            widget: "string"
          - label: "SEO"
            name: "seo"
            widget: "object"
            fields:
              - label: "Tagline"
                name: "tagline"
                width: "string"
          - label: "Location"
            name: "location"
            widget: "object"
            fields:
              - label: "Street address"
                name: "street_address"
                widget: "string"
              - label: "Locality"
                name: "locality"
                widget: "string"
              - label: "Region"
                name: "region"
                widget: "string"
              - label: "Country"
                name: "country"
                widget: "string"
