backend:
  name: "github"
  repo: "acgd-webdev-workshops/realcottages"

media_folder: "images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home page"
        name: "home"
        file: "_data/home.yml"
        fields:
          - label: "Banner"
            name: "banner"
            widget: "object"
            fields:
              - label: "Header"
                name: "header"
                widget: "string"
