backend:
    name: github
    repo: hannahdelaney/realcottages

media_folder: "images/uploads"

collections:
  - name: "website-settings"
    label: "Website Settings"
    files:
      - label: "Website Settings"
        name: "site"
        file: "data/site.yml"
        fields:
          - label: "Tel"
            name: "tel"
            widget: "string"
