backend:
    name: github
    repo: hannahdelaney/realcottages

media_folder: "/images/uploads"

collections:
  - name: "website-settings"
    label: "Website Settings"
    files:
      - label: "Website Settings"
        name: "site"
        file: "_data/site.yml"
        fields:
          - label: "Tel"
            name: "tel"
            widget: "string"
          - label: "Tel display"
            name: "tel_display"
            widget: "string"
          - label: "SEO"
            name: "seo"
            widget: "object"
            fields:
              - label: "Tagline"
                name: "tagline"
                widget: "string"
          - label: "Location"
            name: "location"
            widget: "object"
            fields:
              - label: "Street Address"
                name: "street_address"
                widget: "string"
              - label: "Locality"
                name: "locality"
                widget: "string"
              - label: "Region"
                name: "region"
                widget: "string"
              - label: "Country"
                name: "country"
                widget: "string"
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home page"
        name: "home"
        file: "_data/home.yml"
        fields:
          - label: "Banner"
            name: "banner"
            widget: "object"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "Text"
                name: "text"
                widget: "string"
              - label: "Button"
                name: "button"
                widget: "string"
              - label: "Image"
                name: "image"
                widget: "image"
          - label: "Cottages section"
            name: "cottages"
            widget: "object"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "Text"
                name: "text"
                widget: "string"
              - label: "Button"
                name: "button"
                widget: "string"
          - label: "Blog section"
            name: "blog"
            widget: "object"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "Text"
                name: "text"
                widget: "string"
              - label: "Button"
                name: "button"
                widget: "string"
      - label: "About page"
        name: "about"
        file: "about.md"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Description"
            name: "desc"
            widget: "string"
          - label: "Body"
            name: "body"
            widget: "markdown"
  - label: "Blog Posts"
    name: "blog-posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "blog-post"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Description"
        name: "desc"
        widget: "string"
      - label: "Body"
        name: "body"
        widget: "markdown"

  - label: "Cottages"
    name: "cottages"
    folder: "_cottages"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "cottage"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Description"
        name: "desc"
        widget: "string"
      - label: "Thumbnail Image"
        name: "thumb"
        widget: "image"
      - label: "Price"
        name: "price"
        widget: "string"
      - label: "Built in"
        name: "built_in"
        widget: "number"
      - label: "Bedrooms"
        name: "beds"
        widget: "number"
      - label: "Bathrooms"
        name: "baths"
        widget: "number"
      - label: "Address"
        name: "addr"
        widget: "object"
        fields:
          - label: "Street"
            name: "street"
            widget: "string"
          - label: "Locality"
            name: "locality"
            widget: "string"
          - label: "Region"
            name: "region"
            widget: "string"
      - label: "Body"
        name: "body"
        widget: "markdown"
      - label: "Photos"
        name: "photos"
        widget: "list"
        fields:
          - label: "Image"
            name: "url"
            widget: "image"
          - label: "Caption"
            name: "caption"
            widget: "string"
